name: app

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
        working-directory: .
      - name: Run ESLint
        run: yarn lint
        working-directory: .
